// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdtkyhmafwbelzsqxljx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkdGt5aG1hZndiZWx6c3F4bGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNDE5OTIsImV4cCI6MjA2NjkxNzk5Mn0.ruIqGJcWbXYYbsoBdyxto6_lX5Njo-rufExvjyyHdlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});